version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "olympic-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-iwej9jetlz18"
s3_prefix = "olympic-api"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
